### ISSUE TITLE
ability to redirect removed duplicates to remaining entity

### ISSUE THREAD

**Issue by Schaubroeck** [v-ict-or/oslo_xml_schemas#11]
If duplicates are removed from a dataset, the duplicates will be marked as removed, but there should be a way to redirect anyone that used those duplicates to the one that remains active.

**Comment by laurensdv** [comment]
A single directed relation (replacedBy/revisionOf) will be supported to indicate that a resource has been replace by another resource using its identification metadata (oslo:Identifier).

e.g. in the case of RDF the newer/merged version will refer to the previous using http://www.w3.org/TR/prov-o/#wasRevisionOf

**Comment by laurensdv** [comment]
Changes should be reflected in new branch shared_catalogue_extension: https://github.com/rafbuyle/oslo_xml_schemas/tree/shared_catalogue_extension
