### ISSUE TITLE
oslo:Code has incompatible interpretations

### ISSUE THREAD

**Issue by RubenVerborgh** [v-ict-or/oslo_xml_schemas#12]
**Problem:** The `oslo:Code` construct from the vocabulary can and does not work, because its intended usage is incompatible with the RDF model.

**Proposed resolution:** remove and replace by another construct.

**Detailed explanation:** see below.
### Background: the way the RDF model works

Take for example:

```
<http://ex.org/id/nace2008/123456> a skos:Concept.
```

According to RDF semantics, the above means

> The resource identified by `http://ex.org/id/nace2008/123456` is a concept.

Note that the above does **not** mean

> ~~`http://ex.org/id/nace2008/123456` is a concept.~~

This is because `http://ex.org/id/nace2008/123456` is an URL—an identifier, a string of characters—but certainly _not_ a concept. Furthermore, the RDF model does not support the interpretation of a triple as stating something about the IRI of its subject; it does support stating the interpretation as stating something about the resource _identified_ by that IRI.
### Incorrect semantics currently given to `oslo:Code`

If we follow the semantics of the RDF model, in analogy to the above, then:

```
<http://ex.org/id/nace2008/123456> a oslo:Code.
```

**must** mean

> The resource identified by `http://ex.org/id/nace2008/123456` is an OSLO code.

and it **cannot** mean

> ~~`http://ex.org/id/nace2008/123456` is an OSLO code.~~

Unfortunately, this latter interpretation seems to be given to `oslo:Code`, even though this interpretation is impossible in the RDF model.
### Consequences

While this might seem a purely theoretical issue, it is not. We are currently running into problems defining OSLO codes because of this.
### Solutions

To express the notion that _“Y is the OSLO code of the resource identified by X”_, you could use:

```
<X> oslo:hasCode "Y"^^xsd:anyURI.
```

or, more concretely for the above example:

```
<http://ex.org/id/nace2008/123456> oslo:hasCode "http://ex.org/id/nace2008/123456"^^xsd:anyURI.
```

**Comment by laurensdv** [comment]
I agree with this clarification and I recognise this issue,

however the OSLO vocabulary is aligned to the ISA Core Business Vocabulary (now regorg).

And adopted the concept Code from there to extend that core vocabulary where Code was represented as a skos:Concept
http://philarcher.org/isa/business-v1.00.html#skos:Concept
or the final adaption in:
http://www.w3.org/TR/vocab-regorg/
where we especially align to fill in http://www.w3.org/TR/vocab-regorg/#ref_rov_orgActivity
and which has range skos:Concept

To make clear that we extended this interpretation we defined

oslo:Code as a subclass for skos:Concept

However, if this introduces these issues; maybe the best fix would be to reuse skos:Concept rather then making a subclass for it.

Unless skos:Concept would be wrong in this case as well?

**Comment by RubenVerborgh** [comment]
> however the OSLO vocabulary is aligned to the ISA Core Business Vocabulary (now regorg).

Err yeah but… OSLO is the one that introduces the _oslo:Code_ concept, right?
And—that's the issue here—it did so in a way that's incompatible with the RDF model.

> And adopted the concept Code from there to extend that core vocabulary where Code was represented as a skos:Concept

Nothing wrong with `skos:Concept`, if the RDF model is followed.

> we defined oslo:Code as a subclass for skos:Concept
> However, if this introduces these issues;

No, it's not this that introduces the issues.
It's the incorrect interpretation of the RDF model (see above, section “Incorrect semantics”).

> Unless skos:Concept would be wrong in this case as well?

Interpreting `<x> a skos:Concept` as “x is a concept” is wrong.
Interpreting `<x> a skos:Concept` as “_the resource identified by x_ is a concept” is right.

**Comment by nvdk** [comment]
Ruben, can you provide a practical example of your issue? Is it related to the rdfs:comment of oslo:Code or the formal specification?

**Comment by RubenVerborgh** [comment]
**Practical example**

According to the RDF model

```
<http://productencatalogus.vlaanderen.be/fiche/62> a skos:Concept.
```

means that “the thing identified by http://productencatalogus.vlaanderen.be/fiche/62 is a SKOS concept."
So concretely, this means that "Budgetbegeleiding is a SKOS concept”.

However, according to the `oslo:Code` specification,

```
<http://productencatalogus.vlaanderen.be/fiche/62> a oslo:Code.
```

_should_ mean that “http://productencatalogus.vlaanderen.be/fiche/62 is an OSLO Code”.
So concretely, this _should_ mean that the string `h t t p colon slash slash p r…` is an OSLO code.

Yet, this is interpretation is impossible in RDF. The only possible meaning of the above is that "Budgetbegeleiding is an OSLO code”, which is incorrect.

**Comment by madnificent** [comment]
That is an een interesting interpretation of the RDF and/or RDFS model.  The way I see it, the `oslo:Code` is specified to be an `rdfs:subClassOf` of `skos:Concept`.  Well, that's what the _formal_ oslo spec reads anyway.

In the interpretation of the formal oslo spec any `oslo:Code` is a `skos:Concept`.  I don't see anything that would infer that the resource identified by `<http://productencatalogus.vlaanderen.be/fiche/62>` would need to be an `rdfs:Class`.  Hence I can both say

   `<http://productencatalogus.vlaanderen.be/fiche/62> a skos:Concept.`

and

   `<http://productencatalogus.vlaanderen.be/fiche/62> a skos:Code.`

and be valid OWL-DL (and more funky is available in OWL-FULL, if I'd prefer to go that route).  Neither of these seem to specify anything inconsistent.  That is, unless you extended the ontology or imported extensions from some external source.

Could you please clarify further on what you interpret to be RDF?  If we are not interpreting RDFS, but just the raw triple content, then the only thing that may possibly be wrong would be if a primitive would be used to identify a node... I don't see any evidence of that anywhere, so _if you do_, please clarify in which ontology, which version, and where you downloaded it.  If this isn't the issue, then the only issue that may arise is due to the _interpretation_ of the triples.  Have you discovered an issue with OWL or RDFS, or the combination of both?  Is there a reasoner backing your findings?

It's kind-of hard to distil the issue from the content you provided.  We would need the concrete rules which turn into the conflict you are trying to describe to discuss this further.  Thanks.

**Comment by RubenVerborgh** [comment]
@madnificent Thanks for your reaction, but I'm not sure if we're talking about the same thing here.
Of course  `fiche:62 a skos:Concept, oslo:Code.` is possible.

My issue here is about the _interpretation_ of the latter. What does the following mean to you?

```
<http://productencatalogus.vlaanderen.be/fiche/62> a oslo:Code.
```

Does it mean:
a) The string of characters `h t t p colon slash slash p r…` is an OSLO code?
b) The entity Budgetbegeleiding is an OSLO code?

**Comment by madnificent** [comment]
You would say that the resource identified by `<http://productencatalogus.vlaanderen.be/fiche/62>` is an `oslo:Code`.   If I dereference `<http://productencatalogus.vlaanderen.be/fiche/62>` and include that content, then it would include

   `<http://productencatalogus.vlaanderen.be/fiche/62> dc:title "Budgetbegeleiding".`

The URI is like a pointer.  It has no meaning, but to identify a resource.

**Comment by RubenVerborgh** [comment]
So option b?

**Comment by nvdk** [comment]
I agree with @madnificent. This also seams to be the intention looking at the OSLO_model_v1_1_0.png.  A code should be a resource.

**Comment by RubenVerborgh** [comment]
Then I agree with you both, @nvdk and @madnificent, that's indeed the only possible interpretation under the RDF model.

But this might be in conflict with [the spec](http://www.v-ict-or.be/assets/5384d510ce3fb57c500006ad/OSLO1.1-specificaties.pdf#page=21):

> De code wordt gebruikt om te verwijzen naar de sleutel die voorkomt in een bepaalde lijst die 
> gepubliceerd is door een bepaalde bron.

or in English:

> The code is used to point to the key that appears in a certain list published by a certain source.

You say (in accordance with the RDF interpretation of `_:x a oslo:Code`): OSLO codes are resources.
The spec says: OSLO codes point to keys. (So, the identifiers/URIs themselves?)

That's the issue. The correct RDF interpretation is b), while the spec interpretation seems to be a).

**Comment by madnificent** [comment]
The informative specification may be out of sync with the formal spec.

Though not necessary, it would be advised if some predicate was published in the formal specification to link the `oslo:Code`'s `oslo:code` to a unique identifier of that `oslo:Code`'s resource.  The linked code needn't be a resource and may be a primitive value, whilst still allowing us to retrieve the `oslo:Code` if it is stored in our graph or published by an authoritative source.

**Comment by RubenVerborgh** [comment]
**What is the current interpretation then of `oslo:Code` in the formal spec?**
The ontology does not explain this. It says <em>“The Conceptual Model includes a 'Code' datatype…”</em> without defining what exactly that is (and note “datatype”).

I fail to see the meaning (and added value) of declaring a resource an OSLO code. What is it?
A code seems to indicate an identifier, and that's not the case right now.

Note that

```
<http://productencatalogus.vlaanderen.be/fiche/62> a oslo:Code;
                                                   oslo:code "abcdef".
```

would be quite unfortunate: "The OSLO code of the OSLO code is…”.

In my opinion, what you really need is simply:

```
<http://productencatalogus.vlaanderen.be/fiche/62> oslo:code "abcdef".
```

This is also in line with the informative specification (which could be out of date; is there a new version?).

**Comment by nvdk** [comment]
I'm personally in favour of having it as a resource. This means you can add extra information about the code to the node (eg it's publisher, labels in different languages etc). An authoritative source could also publish different codes as LOD.

**Comment by RubenVerborgh** [comment]
@nvdk But define “it”. What _is_ the code?

Note that you could equally have

```
<http://productencatalogus.vlaanderen.be/fiche/62> oslo:code [
    a oslo:Code;  # but NOT a skos:Concept then!
    :publisher <…>;
    :codeValue "abcdef";
    skos:prefLabel "abcdef"@en
].
```

In other words, I think there is a difference between the resource that represents the concept (<em>Budgetbegeleiding</em> in this case) and the resource that represents the code (who assigned it, what are its labels). They seems distinct entities. Whether or not the code is then represented as a literal or as a resource is another point.

**Comment by nvdk** [comment]
I agree with you that fiche:62 is not a oslo:Code and that it could be usefull to have a property defined in the oslo ontology to denote a concept has a certain code. 

I disagree with your proposal that the oslo:Code class needs to be replaced with a property. A skos:Concept is nothing more then a unit of thought. It denotes a knowledge organization, so a code can be a skos:Concept. As such it is useful to create a subclass for resources of such a type.

**Comment by RubenVerborgh** [comment]
> I agree with you that fiche:62 is not a oslo:Code

Sadly, this is how I've seen `oslo:Code` being used so far ([example](http://ewi.mmlab.be/cd/all?subject=%3Chttp://productencatalogus.vlaanderen.be/fiche/62%3E)).

Could you define what _is_ an oslo:Code, perhaps by giving an example of one?

> a skos:Concept is nothing more then a unit of though.

Probably shouldn't be a `skos:Concept` then.

> a code can be a skos:Concept

It _is_ defined as `skos:Concept` at the moment, but we _really_ need a definition of an `oslo:Code` if the concept must stay. It seems like nobody is exactly sure about what it is, so this makes it very hard to objectively judge its necessity.

**Comment by nvdk** [comment]
http://data.kbodata.be/nace2003/75130#id would be a good candidate, though it currently isn't typed as a oslo:Code

**Comment by RubenVerborgh** [comment]
@nvdk That could be. I have added a separate issue #13 to track the definition of an OSLO code.

**Comment by laurensdv** [comment]
Until definition of OSLO Code is clear, this discussion continues in https://github.com/rafbuyle/oslo_xml_schemas/issues/13.
